import { AbsoluteFill, Audio, Sequence, staticFile, useCurrentFrame } from "remotion";
import { useSyncedTiming } from "./hooks/useSyncedTiming";
import script from "./data/script.json";

// ---------------------------------------------------------------------------
// Scene placeholder — replaced in Step 3 with per-scene React components.
// Each scene renders its title + key quote with a fade-in so the composition
// is already navigable in Remotion Studio after this step.
// ---------------------------------------------------------------------------

const ScenePlaceholder: React.FC<{ sceneId: string }> = ({ sceneId }) => {
  const frame = useCurrentFrame();
  const timing = useSyncedTiming(sceneId);
  const localFrame = frame - timing.startFrame;
  const fadeFrames = 20;
  const opacity = Math.min(1, localFrame / fadeFrames);

  const scene = script.find((s) => s.id === sceneId);
  if (!scene) return null;

  return (
    <AbsoluteFill className="bg-slate-950 flex flex-col items-center justify-center px-24">
      <div style={{ opacity }} className="text-center space-y-6">
        <p className="text-slate-500 text-lg uppercase tracking-widest font-light">
          {scene.id}
        </p>
        <h2 className="text-white text-5xl font-bold leading-tight max-w-3xl">
          {scene.title}
        </h2>
        <blockquote className="text-amber-400 text-2xl italic max-w-2xl leading-relaxed">
          "{scene.keyQuote}"
        </blockquote>
      </div>
    </AbsoluteFill>
  );
};

// ---------------------------------------------------------------------------
// WhiteTigerSummary — root composition
// Sequences every scene using audio-locked timing from useSyncedTiming.
// ---------------------------------------------------------------------------

export const WhiteTigerSummary: React.FC = () => {
  return (
    <AbsoluteFill className="bg-black">
      {/* Full-length voiceover — generated by generate-audio.ts */}
      <Audio src={staticFile("voiceover.mp3")} />

      {script.map((scene) => (
        <SceneSequence key={scene.id} sceneId={scene.id} />
      ))}
    </AbsoluteFill>
  );
};

// Thin wrapper so each scene can call useSyncedTiming() independently
const SceneSequence: React.FC<{ sceneId: string }> = ({ sceneId }) => {
  const timing = useSyncedTiming(sceneId);

  return (
    <Sequence from={timing.startFrame} durationInFrames={timing.durationFrames}>
      <ScenePlaceholder sceneId={sceneId} />
    </Sequence>
  );
};
